[profile.default]
solc_version = "0.8.26"
src = "contracts"
out = "out"
libs = ["lib"]

[fmt]
line_length = 100
tab_width = 4

remappings = [
  "v4-core/=lib/v4-core/",
  "v4-periphery/=lib/v4-periphery/",
  "@openzeppelin/=lib/openzeppelin-contracts/"
]
