[profile.default]
solc_version = "0.8.26"
src = "contracts"
out = "out"
libs = ["lib"]

[fmt]
line_length = 100
tab_width = 4

remappings = [
    "forge-std/=lib/forge-std/src/",
    "v4-core/=lib/v4-core/",
    "v4-periphery/=lib/v4-periphery/",
    "@uniswap/v4-core/=lib/v4-core/"
]