[profile.default]
solc_version = "0.8.26"
src = "contracts"
out = "out"
libs = ["lib"]

# Enable standard optimizer (safe defaults)
optimizer = true
optimizer_runs = 200

[fmt]
line_length = 100
tab_width = 4

# Remappings (point to repo roots; imports can include /src/… for periphery, and no /src for v4-core due to submodule remap)
remappings = [
  "forge-std/=lib/forge-std/src/",
  "v4-core/=lib/v4-core/src/",            # <- NOTE: this ends with /src/ on purpose
  "v4-periphery/=lib/v4-periphery/",
  "lz/=lib/LayerZero-v2/packages/layerzero-v2/evm/oapp/contracts/",
  "openzeppelin-contracts/=lib/openzeppelin-contracts/"
]

[rpc_endpoints]
unichain_sepolia = "https://sepolia.unichain.org"
unichain_mainnet = "https://rpc.unichain.org"
zircuit_mainnet  = "https://mainnet.zircuit.com"
