[profile.default]
solc_version = "0.8.26"
src = "contracts"
out = "out"
libs = ["lib"]
optimizer = true
optimizer_runs = 200

[fmt]
line_length = 100
tab_width = 4

# Remappings
remappings = [
  "forge-std/=lib/forge-std/src/",
  "v4-core/=lib/v4-core/src/",
  "v4-periphery/=lib/v4-periphery/",
  # Optional alias if you want short imports later:
  "lz/=lib/LayerZero-v2/packages/layerzero-v2/evm/oapp/contracts/",
  "openzeppelin-contracts/=lib/openzeppelin-contracts/",
  # >>> ADD THIS LINE <<<
  "@layerzerolabs/lz-evm-protocol-v2/=lib/LayerZero-v2/packages/layerzero-v2/evm/protocol/"
]

[rpc_endpoints]
unichain_sepolia = "https://sepolia.unichain.org"
unichain_mainnet = "https://rpc.unichain.org"
zircuit_mainnet  = "https://mainnet.zircuit.com"
