[profile.default]
solc_version = "0.8.26"
evm_version  = "cancun"
src  = "contracts"
out  = "out"
libs = ["lib"]
ffi  = true

[fmt]
line_length = 100
tab_width   = 4

# Windows-safe, canonical Uniswap aliases.
remappings = [
  "@uniswap/v4-core/=lib/v4-core/",
  "v4-periphery/=lib/v4-periphery/",
  "@openzeppelin/=lib/openzeppelin-contracts/",
  "forge-std/=lib/forge-std/src/"
]
